### PR TITLE
Activate the COM object with ACTIVATE_32_BIT_SERVER only on XP x64/2003

### PR DESCRIPTION
**Pull request by renodr**
Due to a behavior quick specific to Windows XP x64 and Server 2003 x64, we need to set CLSCTX_ACTIVATE_32_BIT_SERVER only on those versions of Windows. This causes problems on other versions of Windows though (notably 32-bit XP/2000, where a "The Parameter is incorrect" message gets displayed)

Let's work around this by checking specifically for AMD64 versions of Windows NT 5.x. This just includes XP 64-bit and Server 2003 64-bit. For other OSes, let's activate the COM object the way we were previously.

Tested on Windows XP x64 SP2, Windows 2000 Professional with SP4, and Windows XP Professional SP3 x86 with an initial round of updates from Windows Update. Note that there's something strange going on with NSIS with recent commits, resulting in URL Parts Errors (sometimes when downloading the update agent, but I've noticed it occur with the Certificate Trust List as well if the update agent is manually installed). I used the installer from LegacyUpdate 1.5 and then copied the DLL from my Release folder

### CODE REVIEW

**Comment by renodr** [comment]
This should fix #88

**Comment by stdin82** [comment]
Is GetVersionInfo() correct api? or it should be GetVersion()?

**Comment by kirb** [comment]
GetVersionInfo() is correct, it's the helper function in Utils.cpp that caches the result of GetVersionEx().

**Review by kirb — APPROVED** [review]
Looks good, thank you! Surprised GetSystemInfo() rather than Get**Native**SystemInfo() works. Then again, it's a strange quirk as a whole that an x86 binary calls x64 COM objects by default anyway...

**Comment by stdin82** [comment]
> Looks good, thank you! Surprised GetSystemInfo() rather than Get**Native**SystemInfo() works. Then again, it's a strange quirk as a whole that an x86 binary calls x64 COM objects by default anyway...

default rundll32.exe in this case is x64, and GetSystemInfo will return x64 (first condition)
in case running via \SysWOW64\rundll32.exe, GetSystemInfo will return x86 (second condition works too here)

it's a win-win situation :grinning:

**Comment by kirb** [comment]
That bit makes sense, but then, it's a 32-bit dll somehow executing in a 64-bit process! I assumed that was always a no-go. Maybe rundll32 has some special handling for that, or maybe it "works" on NT 5.2 but isn't supposed to? I've never seen mixed 32/64 memory spaces implemented on any platform, hopefully it's safe and isn't likely to cause undefined behavior.

**Comment by stdin82** [comment]
Well, Procmon shows that 64-bit rundll32.exe eventually redirect the call to 32-bit rundll32.exe which "Load Image" LegacyUpdate.dll
this happens in all versions

**Pull request merged**
